# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57be196cc0cc1dcb9877f4ab79180a98f2dba95e90a2693048c6d77f432fee0cb894aaa69a3e8edc4c8ea71e6886d3c3610908028439be803114bfbaeb530724

test:
  secret_key_base: 506fd2f9d2e64cd9af2cd114fc7bffcbdeed9c7093a67ec5906151aff44d0f779fbced3164edb9b38459532655ca5e49483c374a38ec6e0c1467c27ba89d6c42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
